### ISSUE TITLE
Can you share the evaluation datasets ?

### ISSUE THREAD

**Issue by tienthanhdhcn** [tomkocmi/LanideNN#4]
Hi @kocmitom, thanks for the great work. Can you share the evaluation datasets used in the work (e.g., EuroGov, TLC, Wikipedia)?

**Comment by kocmitom** [comment]
Hi @tienthanhdhcn ... thanks for the question. It is a bit older work. But this should be the testset:
https://1drv.ms/t/s!Aq0goPMF_Lnlg-Jf47U0VGYAJL46qA?e=feDcS7

**Comment by tienthanhdhcn** [comment]
Thank you so much @kocmitom . I already got the LanideNN test set from your github and that is great. However, I want to make the comparison on other test sets as well. Please can you kindly point me to other tests (EuroGov, TLC, Wikipedia) and where can I download them?

Again, thanks for your great help,

**Comment by kocmitom** [comment]
We did not create those testsets, but as we write in the paper, they are from Baldwin and Lui 2010. https://www.aclweb.org/anthology/N10-1027.pdf 
if they are no longer available, you need to ask the authors. Unfortunately, I don't have them anymore.

**Comment by tienthanhdhcn** [comment]
Thanks @kocmitom so much
